Sudoku laba
kirglushkov/cs102 pull request #5
Opened 2021-11-13 12:20 UTC by kirglushkov

2021-12-30 14:02 UTC, anastasiiaCher approved these changes

2021-12-30 14:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [x for x in grid[a]]
слишком много лишних движений

2021-12-30 14:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [x[b] for x in grid]
`b` можно не вводить

2021-12-30 14:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                    fin_pos.append(hcae)
три вложенных цикла - худший кошмар интерпретатора, необходимо написать по-другому

2021-12-30 14:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                    summa2.append(int(each))
если у вас есть только добавление в конец внутри цикла, то списковое включение будет лучше

2021-12-30 14:07 UTC, anastasiiaCher requested changes
случайно вам одобрила пул-реквест(

2021-12-30 17:24 UTC, kirglushkov commented on homework02/sudoku.py
> +                    summa2.append(int(each))
переделал!

2022-01-17 04:44 UTC, anastasiiaCher approved these changes

2022-01-19 08:03 UTC, merged