Maze
kirglushkov/cs102 pull request #8
Opened 2021-12-18 13:11 UTC by kirglushkov

2021-12-30 14:06 UTC, anastasiiaCher requested changes

2021-12-30 14:06 UTC, anastasiiaCher commented on homework04_new/maze.py
> +    for i, j in enumerate(empty_cells):
вместо `i` можно взять пустую переменную `_`

2021-12-30 14:06 UTC, anastasiiaCher commented on homework04_new/maze.py
> +    return exits
настоятельно рекомендую полюбить списковые включения

2021-12-30 14:06 UTC, anastasiiaCher commented on homework04_new/maze.py
> +                for x, y in ways:
три вложенных цикла - повод задуматься об эффективности решения

2021-12-30 17:28 UTC, kirglushkov commented on homework04_new/maze.py
> +    for i, j in enumerate(empty_cells):
ок

2021-12-30 17:30 UTC, kirglushkov commented on homework04_new/maze.py
> +    return exits
ок

2022-01-17 04:45 UTC, anastasiiaCher approved these changes

2022-01-19 08:03 UTC, merged